steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - cicd_2
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python37
      - --allow-unauthenticated
      - --entry-point=devops
      - --memory=512MB
      - --timeout=120s
